BEGIN;

ALTER TABLE neuro.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.user_preferences DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.generations DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.generation_assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.metacoin_ledger DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.promo_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.promo_redemptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.referral_relations DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.referral_earnings DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.referral_withdrawals DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.voice_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.product_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.telegram_updates DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.telegram_api_calls DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.provider_api_calls DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.provider_webhooks DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.delivery_attempts DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.system_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.free_weekly_usage DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.free_request_claims DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.free_weekly_entitlement_usage DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.free_entitlement_claims DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.legal_consent_status DISABLE ROW LEVEL SECURITY;
ALTER TABLE neuro.legal_consent_events DISABLE ROW LEVEL SECURITY;

REVOKE ALL ON SCHEMA neuro FROM PUBLIC;
REVOKE ALL ON SCHEMA neuro FROM anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA neuro FROM anon, authenticated;
REVOKE ALL ON ALL ROUTINES IN SCHEMA neuro FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA neuro FROM anon, authenticated;

GRANT USAGE ON SCHEMA neuro TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA neuro TO service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA neuro TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA neuro TO service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA neuro
  REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA neuro
  GRANT ALL ON TABLES TO service_role;

NOTIFY pgrst, 'reload schema';

COMMIT;
